-- Reference data: common PSX tickers + sectors (used to enrich imports).
insert into public.stock_master (ticker, company_name, sector) values
  ('MEBL',  'Meezan Bank Limited',                     'Commercial Banks'),
  ('FFC',   'Fauji Fertilizer Company Limited',        'Fertilizer'),
  ('HUBC',  'The Hub Power Company Limited',           'Power Generation & Distribution'),
  ('SYS',   'Systems Limited',                         'Technology & Communication'),
  ('ENGRO', 'Engro Holdings Limited',                  'Conglomerate'),
  ('OGDC',  'Oil & Gas Development Company Limited',   'Oil & Gas Exploration'),
  ('PPL',   'Pakistan Petroleum Limited',              'Oil & Gas Exploration'),
  ('PSO',   'Pakistan State Oil Company Limited',      'Oil & Gas Marketing'),
  ('LUCK',  'Lucky Cement Limited',                    'Cement'),
  ('MLCF',  'Maple Leaf Cement Factory Limited',       'Cement'),
  ('DGKC',  'D.G. Khan Cement Company Limited',        'Cement'),
  ('UBL',   'United Bank Limited',                     'Commercial Banks'),
  ('MCB',   'MCB Bank Limited',                        'Commercial Banks'),
  ('HBL',   'Habib Bank Limited',                      'Commercial Banks'),
  ('BAFL',  'Bank Alfalah Limited',                    'Commercial Banks'),
  ('BAHL',  'Bank AL Habib Limited',                   'Commercial Banks'),
  ('EFERT', 'Engro Fertilizers Limited',               'Fertilizer'),
  ('FATIMA','Fatima Fertilizer Company Limited',       'Fertilizer'),
  ('KAPCO', 'Kot Addu Power Company Limited',          'Power Generation & Distribution'),
  ('KEL',   'K-Electric Limited',                      'Power Generation & Distribution'),
  ('TRG',   'TRG Pakistan Limited',                    'Technology & Communication'),
  ('NETSOL','NetSol Technologies Limited',             'Technology & Communication'),
  ('AVN',   'Avanceon Limited',                        'Technology & Communication'),
  ('PTC',   'Pakistan Telecommunication Company Ltd',  'Technology & Communication'),
  ('MARI',  'Mari Energies Limited',                   'Oil & Gas Exploration'),
  ('POL',   'Pakistan Oilfields Limited',              'Oil & Gas Exploration'),
  ('ATRL',  'Attock Refinery Limited',                 'Refinery'),
  ('NRL',   'National Refinery Limited',               'Refinery'),
  ('SEARL', 'The Searle Company Limited',              'Pharmaceuticals'),
  ('AGP',   'AGP Limited',                             'Pharmaceuticals'),
  ('GLAXO', 'GlaxoSmithKline Pakistan Limited',        'Pharmaceuticals'),
  ('ILP',   'Interloop Limited',                       'Textile Composite'),
  ('NML',   'Nishat Mills Limited',                    'Textile Composite'),
  ('GATM',  'Gul Ahmed Textile Mills Limited',         'Textile Composite'),
  ('ISL',   'International Steels Limited',            'Engineering'),
  ('MUGHAL','Mughal Iron & Steel Industries Limited',  'Engineering'),
  ('MTL',   'Millat Tractors Limited',                 'Automobile Assembler'),
  ('INDU',  'Indus Motor Company Limited',             'Automobile Assembler'),
  ('HCAR',  'Honda Atlas Cars (Pakistan) Limited',     'Automobile Assembler'),
  ('PAEL',  'Pak Elektron Limited',                    'Cable & Electrical Goods'),
  ('NESTLE','Nestle Pakistan Limited',                 'Food & Personal Care'),
  ('FFL',   'Fauji Foods Limited',                     'Food & Personal Care'),
  ('UNITY', 'Unity Foods Limited',                     'Food & Personal Care'),
  ('AIRLINK','Air Link Communication Limited',         'Technology & Communication'),
  ('CNERGY','Cnergyico PK Limited',                    'Refinery'),
  ('SSGC',  'Sui Southern Gas Company Limited',        'Oil & Gas Marketing'),
  ('SNGP',  'Sui Northern Gas Pipelines Limited',      'Oil & Gas Marketing')
on conflict (ticker) do nothing;
