/* eslint-disable @next/next/no-html-link-for-pages -- export endpoint returns a file, not a page */
import Link from "next/link";
import { createClient, getUser } from "@/lib/supabase/server";
import { getPerformanceAnalytics } from "@/lib/engine/performance";
import { getPortfolio } from "@/lib/portfolio";
import { EmptyState } from "@/components/empty-state";
import { ActionButton } from "@/components/action-button";
import { Button } from "@/components/ui/button";
import { cn, formatMoney, formatNumber, formatSignedPct } from "@/lib/utils";
import { ChevronDown, Download, RefreshCw, TrendingUp, Upload } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function PerformancePage() {
  const supabase = await createClient();
  const user = await getUser();
  if (!user) return null;
  const [analytics, portfolio] = await Promise.all([getPerformanceAnalytics(supabase, user.id), getPortfolio(supabase, user.id)]);

  if (!analytics) return <div className="space-y-5"><header><p className="eyebrow">Portfolio</p><h1 className="mt-1 text-2xl font-semibold">Performance</h1></header><EmptyState icon={TrendingUp} title="No ledger found" description="Import an AKD Statement of Account to calculate ledger-backed return, cash flows and trade costs." action={<Link href="/import"><Button><Upload className="h-4 w-4" /> Import statement</Button></Link>} /></div>;

  const { returns, friction, byYear, sales } = analytics;
  const currentWorth = portfolio.totalValue + portfolio.cashBalance;
  const netGain = currentWorth - returns.totalDeposited;
  const buyOrders = byYear.reduce((sum, row) => sum + row.tradeCount, 0) - sales.length;
  const bridge = [
    { label: "Capital contributed", value: returns.totalDeposited, tone: "base" },
    { label: "Realised P/L", value: returns.realizedPl, tone: returns.realizedPl >= 0 ? "positive" : "negative" },
    { label: "Unrealised P/L", value: portfolio.unrealizedPl, tone: portfolio.unrealizedPl >= 0 ? "positive" : "negative" },
    { label: "Net dividends", value: portfolio.dividendIncome, tone: "positive" },
    { label: "Total friction", value: -friction.total, tone: "negative" },
    { label: "Current net worth", value: currentWorth, tone: "base" },
  ];

  return <div className="space-y-7 pb-4">
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-border pb-5"><div><p className="eyebrow">Portfolio</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Performance</h1><p className="mt-1 text-sm text-muted-foreground">Ledger-backed return, cash-flow and cost analysis.</p><p className="mt-3 text-xs text-muted-foreground">AKD ledger synced through 22 Jun 2026 · Current portfolio values include the 24 Jun manual purchases.</p></div><div className="flex flex-wrap items-start gap-2"><ActionButton endpoint="/api/import/sync-cash" label={<><RefreshCw className="h-3.5 w-3.5" /> Sync ledger</>} variant="outline" size="sm" /><a href="#reconciliation"><Button variant="outline" size="sm">Review adjustments</Button></a><details className="relative"><summary className="inline-flex h-10 cursor-pointer list-none items-center gap-1.5 rounded-md border border-border bg-card px-3 text-xs font-medium md:h-8">More <ChevronDown className="h-3.5 w-3.5" /></summary><div className="absolute right-0 z-20 mt-1 w-40 rounded-md border border-border bg-card p-1.5 shadow-[var(--shadow-card)]"><a href="/api/export/holdings" className="block rounded px-2 py-1.5 text-xs hover:bg-muted"><Download className="mr-1 inline h-3.5 w-3.5" />Export holdings</a></div></details></div></header>

    <section className="grid border-y border-border sm:grid-cols-2 lg:grid-cols-4"><Metric label="Current net worth" value={formatMoney(currentWorth)} sub="Market value plus cash" /><Metric label="Net investment gain" value={formatMoney(netGain)} sub={formatSignedPct(returns.totalDeposited ? netGain / returns.totalDeposited * 100 : null)} tone={netGain >= 0 ? "positive" : "negative"} /><Metric label="XIRR" value={returns.xirrPct !== null ? `${returns.xirrPct}%` : "Unavailable"} sub={`${returns.holdingPeriodYears} years · money-weighted`} tone={returns.xirrPct !== null && returns.xirrPct > 0 ? "positive" : undefined} /><Metric label="Capital contributed" value={formatMoney(returns.totalDeposited)} sub="Dated external broker deposits" /><Metric label="Realised P/L" value={formatMoney(returns.realizedPl)} sub={`${sales.length} sell order${sales.length === 1 ? "" : "s"}`} tone={returns.realizedPl >= 0 ? "positive" : "negative"} /><Metric label="Unrealised P/L" value={formatMoney(portfolio.unrealizedPl)} sub="Current priced holdings" tone={portfolio.unrealizedPl >= 0 ? "positive" : "negative"} /><Metric label="Net dividends" value={formatMoney(portfolio.dividendIncome)} sub="Dividend Income ledger" /><Metric label="Total friction" value={formatMoney(friction.total)} sub={`${friction.pctOfDeposits}% of contributions`} tone="negative" /></section>

    <section className="border-t border-border pt-5"><h2 className="text-lg font-semibold">Wealth creation bridge</h2><p className="mt-1 text-xs text-muted-foreground">Traceable bridge from external capital to current net worth. Trade fees are included once in realised/unrealised results and shown separately for audit.</p><div className="mt-5 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{bridge.map((item) => <div key={item.label} className="border-l border-border pl-3"><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{item.label}</p><p className={cn("mt-1 text-base font-semibold tabular-nums", item.tone === "positive" ? "text-emerald-700" : item.tone === "negative" ? "text-red-700" : "")}>{formatMoney(item.value)}</p></div>)}</div></section>

    <div className="grid gap-7 xl:grid-cols-[1.25fr_0.75fr]"><section className="border-t border-border pt-5"><h2 className="text-lg font-semibold">Performance by year</h2><p className="mt-1 text-xs text-muted-foreground">Full broker-ledger deposits, trading activity, realised results and recorded friction.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-xs"><thead><tr className="border-b border-border text-left text-[10px] uppercase tracking-wide text-muted-foreground"><th className="px-2 py-2">Year</th><th className="px-2 py-2 text-right">Contributed</th><th className="px-2 py-2 text-right">Purchases</th><th className="px-2 py-2 text-right">Sales</th><th className="px-2 py-2 text-right">Realised P/L</th><th className="px-2 py-2 text-right">Friction</th><th className="px-2 py-2 text-right">Orders</th></tr></thead><tbody>{byYear.map((row) => <tr key={row.year} className="border-b border-border last:border-0"><td className="px-2 py-2 font-semibold">{row.year}</td><td className="px-2 py-2 text-right tabular-nums">{formatNumber(row.deposits, 0)}</td><td className="px-2 py-2 text-right tabular-nums">{formatNumber(row.buys, 0)}</td><td className="px-2 py-2 text-right tabular-nums">{formatNumber(row.sells, 0)}</td><td className={cn("px-2 py-2 text-right tabular-nums", row.realizedPl >= 0 ? "text-emerald-700" : "text-red-700")}>{formatSignedPct(row.realizedPl)}</td><td className="px-2 py-2 text-right tabular-nums">{formatNumber(row.friction, 0)}</td><td className="px-2 py-2 text-right tabular-nums">{row.tradeCount}</td></tr>)}</tbody></table></div></section>
    <section className="border-t border-border pt-5"><h2 className="text-lg font-semibold">Trading costs</h2><p className="mt-1 text-xs text-muted-foreground">Actual costs extracted from the AKD statement.</p><dl className="mt-4 divide-y divide-border text-sm"><Cost label="Brokerage commission" value={friction.commission} /><Cost label="SST" value={friction.sst} /><Cost label="CDC transaction charges" value={friction.cdc} /><Cost label="Account and maintenance" value={friction.accountFees} /><Cost label="CGT and tariffs" value={friction.cgt} /><Cost label="Total friction" value={friction.total} strong /></dl><div className="mt-5"><p className="text-xs font-semibold">Order-size analysis</p>{friction.bySize.map((row) => <div key={row.bucket} className="mt-2 flex justify-between text-xs"><span>{row.bucket} · {row.trades} orders</span><span className="tabular-nums text-muted-foreground">avg {formatNumber(row.avgGross, 0)} · {row.avgFeePct}% charge rate</span></div>)}</div></section></div>

    <section className="border-t border-border pt-5"><h2 className="text-lg font-semibold">Realised performance</h2><p className="mt-1 text-xs text-muted-foreground">Weighted-average cost allocated to each recorded sale. Positions with remaining shares are not treated as closed.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-xs"><thead><tr className="border-b border-border text-left text-[10px] uppercase tracking-wide text-muted-foreground"><th className="px-2 py-2">Ticker</th><th className="px-2 py-2">Sale date</th><th className="px-2 py-2 text-right">Qty sold</th><th className="px-2 py-2 text-right">Cost allocated</th><th className="px-2 py-2 text-right">Net proceeds</th><th className="px-2 py-2 text-right">Realised P/L</th></tr></thead><tbody>{sales.map((sale, index) => <tr key={`${sale.ticker}-${sale.date}-${index}`} className="border-b border-border last:border-0"><td className="px-2 py-2 font-semibold">{sale.ticker}</td><td className="px-2 py-2 tabular-nums text-muted-foreground">{sale.date ?? "—"}</td><td className="px-2 py-2 text-right tabular-nums">{sale.quantity}</td><td className="px-2 py-2 text-right tabular-nums">{formatNumber(sale.costOut, 0)}</td><td className="px-2 py-2 text-right tabular-nums">{formatNumber(sale.proceeds, 0)}</td><td className={cn("px-2 py-2 text-right font-medium tabular-nums", sale.realized >= 0 ? "text-emerald-700" : "text-red-700")}>{formatMoney(sale.realized)}</td></tr>)}</tbody></table></div></section>

    <section id="reconciliation" className="border-t border-border pt-5"><h2 className="text-lg font-semibold">Ledger reconciliation</h2><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-3"><Check label="Broker cash movements" detail="AKD ledger balance reconciles to statement control total." /><Check label="Buy and sell transactions" detail={`${buyOrders} buy orders and ${sales.length} sell orders parsed from the ledger.`} /><Check label="Current inventory" detail="Statement inventory provides the ledger valuation checkpoint." /><Check label="Manual 24 Jun purchases" detail="FFC and FCCL purchases recorded after the statement ledger end date." /><Check label="Corporate adjustments" detail="IREIT, SLM, UBL split and FFBL→FFC conversion are retained for review." /></div><details className="mt-4 text-xs text-muted-foreground"><summary className="cursor-pointer font-medium text-foreground">XIRR methodology and data lineage</summary><p className="mt-2">XIRR uses dated external broker deposits as negative investor cash flows and the ledger net worth as the terminal positive cash flow. It does not use purchases or sales as investor cash flows. Cash-flow-matched KSE-100 comparison is unavailable because matching historical benchmark levels are not stored.</p></details></section>
  </div>;
}

function Metric({ label, value, sub, tone }: { label: string; value: string; sub: string; tone?: "positive" | "negative" }) { return <div className="border-b border-border py-4 last:border-b-0 sm:px-4 sm:first:pl-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p><p className={cn("mt-1 text-lg font-semibold tabular-nums", tone === "positive" ? "text-emerald-700" : tone === "negative" ? "text-red-700" : "")}>{value}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{sub}</p></div>; }
function Cost({ label, value, strong = false }: { label: string; value: number; strong?: boolean }) { return <div className="flex justify-between py-2"><dt className={cn(strong && "font-semibold")}>{label}</dt><dd className={cn("tabular-nums", strong && "font-semibold")}>{formatMoney(value)}</dd></div>; }
function Check({ label, detail }: { label: string; detail: string }) { return <div className="border-l-2 border-emerald-600 pl-3"><p className="font-medium">{label}</p><p className="mt-0.5 text-xs text-muted-foreground">{detail}</p></div>; }
