"use client";

import { useMemo, useState } from "react";
import { SectorBarsLazy, MarketHeatmapLazy, MoversBoardLazy } from "@/components/market/lazy";
import { fmtCompact, fmtPct, tone } from "@/lib/market/format";
import { cn } from "@/lib/utils";
import type { EventRow, ItemRow, MoverRow, SectorRow } from "@/lib/market/read";
import type { ForeignFlowHistory, ForeignFlowSnapshot } from "@/lib/market/foreign-flows";

type LeadershipView = "top-bottom" | "portfolio" | "all";
type LeadershipMetric = "return" | "volume" | "value";
type ExploreTab = "heatmap" | "movers" | "sectors" | "events";
type FlowTab = "foreign" | "sectors" | "local" | "history";

export function MarketPulseWorkspace({ sectors, heatmap, movers, events, owned, watched, foreignFlow, flowHistory }: { sectors: SectorRow[]; heatmap: ItemRow[]; movers: Record<string, MoverRow[]>; events: EventRow[]; owned: string[]; watched: string[]; foreignFlow: ForeignFlowSnapshot | null; flowHistory: ForeignFlowHistory }) {
  const [leadershipView, setLeadershipView] = useState<LeadershipView>("top-bottom");
  const [metric, setMetric] = useState<LeadershipMetric>("return");
  const [flowTab, setFlowTab] = useState<FlowTab>("foreign");
  const [exploreTab, setExploreTab] = useState<ExploreTab>("heatmap");
  const ownedSectors = useMemo(() => new Set(heatmap.filter((item) => owned.includes(item.ticker)).map((item) => item.sector).filter(Boolean)), [heatmap, owned]);
  const ranked = useMemo(() => [...sectors].filter((sector) => sector.average_return !== null).sort((a, b) => metric === "return" ? (b.average_return ?? 0) - (a.average_return ?? 0) : metric === "volume" ? b.total_volume - a.total_volume : b.total_value - a.total_value), [sectors, metric]);
  const selected = leadershipView === "portfolio" ? ranked.filter((sector) => ownedSectors.has(sector.sector)) : leadershipView === "all" ? ranked : ranked;
  const top = leadershipView === "top-bottom" ? ranked.slice(0, 5) : selected.slice(0, 10);
  const bottom = leadershipView === "top-bottom" ? ranked.slice(-5).reverse() : [];

  return <div className="space-y-7">
    <section className="border-t border-border pt-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Market Leadership</h2><p className="mt-1 text-xs text-muted-foreground">Sector performance from the current PSX market snapshot.</p></div><div className="flex flex-wrap gap-1"><Control active={leadershipView === "top-bottom"} onClick={() => setLeadershipView("top-bottom")}>Top & bottom</Control><Control active={leadershipView === "portfolio"} onClick={() => setLeadershipView("portfolio")}>My sectors</Control><Control active={leadershipView === "all"} onClick={() => setLeadershipView("all")}>All sectors</Control></div></div><div className="mt-3 flex gap-1"><Control active={metric === "return"} onClick={() => setMetric("return")}>Average return</Control><Control active={metric === "volume"} onClick={() => setMetric("volume")}>Volume</Control><Control active={metric === "value"} onClick={() => setMetric("value")}>Traded value</Control></div><div className={cn("mt-5 grid gap-7", bottom.length ? "lg:grid-cols-2" : "")}>{top.length ? <LeadershipList title={leadershipView === "top-bottom" ? "Top sectors" : "Selected sectors"} rows={top} metric={metric} /> : <p className="text-sm text-muted-foreground">No portfolio-sector data is available.</p>}{bottom.length > 0 && <LeadershipList title="Bottom sectors" rows={bottom} metric={metric} />}</div></section>

    <section className="border-t border-border pt-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Investor Flows</h2><p className="mt-1 text-xs text-muted-foreground">Latest available investor-flow data and stored reporting history.</p></div><div className="flex gap-1 rounded-md bg-muted p-0.5">{(["foreign", "sectors", "local", "history"] as FlowTab[]).map((tab) => <button key={tab} onClick={() => setFlowTab(tab)} className={cn("rounded px-2.5 py-1.5 text-xs capitalize", flowTab === tab && "bg-card shadow-sm")}>{tab === "local" ? "Local investors" : tab}</button>)}</div></div><div className="mt-5"><FlowView tab={flowTab} snapshot={foreignFlow} history={flowHistory} /></div></section>

    <section className="border-t border-border pt-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Explore the Market</h2><p className="mt-1 text-xs text-muted-foreground">Open one detailed market view at a time.</p></div><div className="scroll-touch -mx-1 flex gap-1 overflow-x-auto px-1 sm:mx-0 sm:overflow-visible sm:px-0">{(["heatmap", "movers", "sectors", "events"] as ExploreTab[]).map((tab) => <button key={tab} onClick={() => setExploreTab(tab)} className={cn("shrink-0 border-b-2 px-3 py-1.5 text-xs font-medium capitalize", exploreTab === tab ? "border-foreground text-foreground" : "border-transparent text-muted-foreground hover:text-foreground")}>{tab}</button>)}</div></div><div className="mt-5">{exploreTab === "heatmap" && <MarketHeatmapLazy items={heatmap} sectors={[...new Set(heatmap.map((item) => item.sector).filter((sector): sector is string => !!sector))].sort()} owned={owned} watched={watched} />}{exploreTab === "movers" && <MoversBoardLazy movers={movers} owned={owned} watched={watched} />}{exploreTab === "sectors" && <SectorBarsLazy sectors={sectors} />}{exploreTab === "events" && <EventsTable events={events} owned={owned} />}</div></section>
  </div>;
}

function Control({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={cn("rounded px-2.5 py-1.5 text-[11px] font-medium", active ? "bg-foreground text-background" : "bg-muted text-muted-foreground hover:text-foreground")}>{children}</button>; }

function LeadershipList({ title, rows, metric }: { title: string; rows: SectorRow[]; metric: LeadershipMetric }) { const max = Math.max(...rows.map((row) => Math.abs(metric === "return" ? row.average_return ?? 0 : metric === "volume" ? row.total_volume : row.total_value)), 1); return <div><p className="text-xs font-semibold">{title}</p><div className="mt-3 space-y-3">{rows.map((row) => { const value = metric === "return" ? row.average_return ?? 0 : metric === "volume" ? row.total_volume : row.total_value; const positive = metric !== "return" || value >= 0; return <div key={row.sector}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate font-medium">{row.sector}</span><span className={cn("shrink-0 tabular-nums", metric === "return" && positive ? "text-emerald-700" : metric === "return" ? "text-red-700" : "text-muted-foreground")}>{metric === "return" ? fmtPct(value) : fmtCompact(value)} · {row.advancers}↑/{row.decliners}↓</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><span className={cn("block h-full rounded-full", metric === "return" ? positive ? "bg-emerald-600" : "bg-red-600" : "bg-brand")} style={{ width: `${Math.abs(value) / max * 100}%` }} /></div></div>; })}</div></div>; }

function FlowView({ tab, snapshot, history }: { tab: FlowTab; snapshot: ForeignFlowSnapshot | null; history: ForeignFlowHistory }) { if (!snapshot) return <p className="border-y border-border py-5 text-sm text-muted-foreground">No investor-flow data is available yet.</p>; const unit = `${snapshot.day.currency} mn`; if (tab === "foreign") return <div className="grid gap-5 sm:grid-cols-4"><FlowMetric label="Latest available" value={snapshot.day.date} /><FlowMetric label="Net foreign flow" value={`${snapshot.day.fipiNet !== null && snapshot.day.fipiNet > 0 ? "+" : ""}${snapshot.day.fipiNet?.toFixed(1) ?? "—"} ${unit}`} tone={tone(snapshot.day.fipiNet)} /><FlowMetric label="Gross buying" value={`${snapshot.day.fipiGrossBuy?.toFixed(1) ?? "—"} ${unit}`} /><FlowMetric label="Gross selling" value={`${snapshot.day.fipiGrossSell?.toFixed(1) ?? "—"} ${unit}`} /><p className="sm:col-span-4 text-[11px] text-muted-foreground">Source: {snapshot.day.sourceProvider} · {snapshot.series.length}-day cumulative {snapshot.cumulativeNet !== null ? `${snapshot.cumulativeNet > 0 ? "+" : ""}${snapshot.cumulativeNet.toFixed(1)} ${unit}` : "not available"}</p></div>; if (tab === "history") return <div><p className="text-sm font-medium">{history.series.length} reporting day{history.series.length === 1 ? "" : "s"} available</p><p className="mt-1 text-xs text-muted-foreground">7-day, 30-day and 90-day comparisons are only shown when enough reporting days have been collected.</p><div className="mt-4 grid gap-3 sm:grid-cols-4">{history.periods.filter((period) => history.series.length >= period.days).map((period) => <FlowMetric key={period.days} label={period.label} value={period.net === null ? "—" : `${period.net > 0 ? "+" : ""}${period.net.toFixed(1)} ${unit}`} tone={tone(period.net)} />)}</div></div>; const rows = tab === "sectors" ? snapshot.sectors.slice(0, 10).map((row) => ({ label: row.sector, value: row.net ?? 0 })) : snapshot.participants.slice(0, 10).map((row) => ({ label: row.label, value: row.net ?? 0 })); const max = Math.max(...rows.map((row) => Math.abs(row.value)), 1); return <div className="space-y-3">{rows.map((row) => <div key={row.label} className="grid grid-cols-[9rem_minmax(0,1fr)_5rem] items-center gap-2 text-xs"><span className="truncate">{row.label}</span><div className="relative h-4"><span className="absolute inset-y-0 left-1/2 w-px bg-border" />{row.value >= 0 ? <span className="absolute left-1/2 top-0.5 h-3 rounded-r bg-emerald-600" style={{ width: `${Math.abs(row.value) / max * 50}%` }} /> : <span className="absolute right-1/2 top-0.5 h-3 rounded-l bg-red-600" style={{ width: `${Math.abs(row.value) / max * 50}%` }} />}</div><span className={cn("text-right font-medium tabular-nums", row.value > 0 ? "text-emerald-700" : row.value < 0 ? "text-red-700" : "")}>{row.value > 0 ? "+" : ""}{row.value.toFixed(1)}</span></div>)}</div>; }

function FlowMetric({ label, value, tone: flowTone }: { label: string; value: string; tone?: "positive" | "negative" | "flat" }) { return <div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p><p className={cn("mt-1 text-sm font-semibold tabular-nums", flowTone === "positive" ? "text-emerald-700" : flowTone === "negative" ? "text-red-700" : "")}>{value}</p></div>; }

function EventsTable({ events, owned }: { events: EventRow[]; owned: string[] }) { return <div className="overflow-x-auto border-y border-border"><table className="w-full min-w-[620px] text-xs"><thead><tr className="border-b border-border text-left text-[10px] uppercase tracking-wide text-muted-foreground"><th className="px-3 py-2">Ticker</th><th className="px-3 py-2">Event</th><th className="px-3 py-2">Headline</th><th className="px-3 py-2">Date</th></tr></thead><tbody>{events.slice(0, 20).map((event) => <tr key={`${event.ticker}-${event.title}`} className="border-b border-border last:border-0"><td className="px-3 py-2 font-semibold">{event.ticker}{owned.includes(event.ticker) && <span className="ml-1 text-[10px] text-brand">OWNED</span>}</td><td className="px-3 py-2 capitalize text-muted-foreground">{event.event_type.replace(/_/g, " ")}</td><td className="max-w-lg truncate px-3 py-2">{event.title}</td><td className="px-3 py-2 tabular-nums text-muted-foreground">{event.event_date}</td></tr>)}{events.length === 0 && <tr><td colSpan={4} className="px-3 py-8 text-center text-muted-foreground">No official events in this snapshot.</td></tr>}</tbody></table></div>; }
